[package]
name = "spl_irgen"
version = "0.1.0"
edition = "2021"

[dependencies]
inkwell = { version = "0.5.0", features = ["llvm17-0"] }
spl_ast = { version = "0.0.1", path = "../ast" }
spl_parser = { version = "0.0.1", path = "../parser" }